### ISSUE TITLE
Ornage PI 5 Plus Kernel doesn't build

### ISSUE THREAD

**Issue by houstontoca** [orangepi-xunlong/orangepi-build#100]
After trying Orange PI zero2 and being able to easily make a custom kernel and a custom uboot out of your repository, I ordered one PI 5 Plus board, the latest/fastest and the most expensive board you offer, for testing.  I was surprised to see that the kernel tagged with rk3588 out of your repository has errors during the make. This is so unlike the orange pi zero2 experience I had.

I downloaded the kernel tagged orange-pi-5.10-rk3588. Used .config file generated via make rockchip_linux_defconfig
And it doesn't build. Since you already have a prebuilt image for this kernel, you must have the fixed files and a working .config. Could you kindly upload the fixed files and the fixed .config so that others can actually build custom kernels without having to fix build errors? While you are at it, it would be nice if you can upload a working .config for the rk3588 uboot in case others want to modify it. It will take just a few minutes of your time and it would save everyone a whole lot of time and frustration. Most importantly it will bring you more sales. Seeing a good working orange pi zero 2 with a customizable  kernel and a uboot, I ordered 20 additional units for my project and I will be ordering hundreds more in the near future. I would do the same for PI 5 plus board if I am able to make RK3588 kernel and uboot.

Thank you

**Comment by orangepi-xunlong** [comment]
kernel：https://github.com/orangepi-xunlong/orangepi-build/blob/next/external/config/kernel/linux-rockchip-rk3588-legacy.config

u-boot：https://github.com/orangepi-xunlong/u-boot-orangepi/blob/v2017.09-rk3588/configs/orangepi_5_plus_defconfig

**Comment by houstontoca** [comment]
Thank you
