### ISSUE TITLE
3B在进行linux镜像编译时出现unable to fetch问题

### ISSUE THREAD

**Issue by umifly** [orangepi-xunlong/orangepi-build#102]
[ .... ] Cleaning [ package lists ]
[ .... ] Updating [ package lists ]
[ .... ] Temporarily disabling [ initramfs-tools hook for kernel ]
[ .... ] Installing PACKAGE_LIST_FAMILY packages [ ethtool can-utils ]
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/c/can-utils/can-utils_2020.11.0-1_arm64.deb  Could not resolve 'repo.huaweicloud.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[ .... ] Removing PACKAGE_LIST_FAMILY_REMOVE packages [ mpv ]
[ .... ] Installing [ linux-u-boot-legacy-orangepi3b_1.0.0_arm64.deb ]
[ .... ] Installing [ linux-image-legacy-rockchip-rk356x_1.0.0_arm64.deb ]
[ .... ] Installing [ linux-dtb-legacy-rockchip-rk356x_1.0.0_arm64.deb ]
[ .... ] Installing [ orangepi-bsp-cli-orangepi3b_1.0.0_arm64.deb ]
[ .... ] Installing [ orangepi-jammy-desktop-gnome_1.0.0_all.deb ]
[ .... ] Installing [ orangepi-bsp-desktop-orangepi3b_1.0.0_arm64.deb ]
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/f/fonts-wqy-zenhei/fonts-wqy-zenhei_0.9.45-8_all.deb  Could not resolve 'repo.huaweicloud.com'
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/k/keybinder/libkeybinder0_0.3.1-2.1_arm64.deb  Could not resolve 'repo.huaweicloud.com'
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/libx/libxfce4util/libxfce4util-common_4.16.0-1_all.deb  Could not resolve 'repo.huaweicloud.com'
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/libx/libxfce4util/libxfce4util7_4.16.0-1_arm64.deb  Could not resolve 'repo.huaweicloud.com'
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/x/xfconf/xfconf_4.16.0-2_arm64.deb  Could not resolve 'repo.huaweicloud.com'
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/x/xfconf/libxfconf-0-3_4.16.0-2_arm64.deb  Could not resolve 'repo.huaweicloud.com'
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/pool/universe/x/xfce4-volumed/xfce4-volumed_0.2.0-0ubuntu3_arm64.deb  Could not resolve 'repo.huaweicloud.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[ .... ] Installing [ orangepi-firmware_1.0.0_all.deb ]
[ .... ] Installing [ orangepi-config_1.0.0_all.deb ]
[ .... ] Installing [ orangepi-zsh_1.0.0_all.deb ]
[ error ] ERROR in function install_deb_chroot [ ./build.sh:305 -> scripts/main.sh:629 -> scripts/main.sh:598 -> scripts/debootstrap.sh:64 -> scripts/distributions.sh:388 -> scripts/image-helpers.sh:221 -> scripts/general.sh:0 ]
[ error ] Installation of /root/orangepi-zsh_1.0.0_all.deb failed [ orangepi3b jammy yes rockchip-rk356x ]
[ o.k. ] Process terminated 
[ error ] unmount_on_exit() called! [ ./build.sh:305 -> scripts/main.sh:1 -> scripts/image-helpers.sh:0 ]
[ o.k. ] Unmounting [ /home/umi/orangepi-build/.tmp/rootfs-b21599f9-1bc2-4011-87ca-0c7bc21b065e/ ]
[ error ] ERROR in function unmount_on_exit [ ./build.sh:305 -> scripts/main.sh:1 -> scripts/image-helpers.sh:90 -> scripts/general.sh:0 ]
[ error ] debootstrap-ng was interrupted 
[ o.k. ] Process terminated

**Comment by umifly** [comment]
确认网络不存在问题，在挂了代理的情况下依然复现

**Comment by umifly** [comment]
在编译jammy+gonme会出现问题，编译服务器版不会出现

**Comment by Q1anWan** [comment]
我现在使用国内镜像(userpatches/config-default.conf 中 CHINA_DOWNLOAD_MIRROR具有值时)，为CM4编译时在最终的Installing [xxx.deb] 阶段也出现了大量unable to fetch error
我通过将CHINA_DOWNLOAD_MIRROR注释掉解决了这个问题。推测可能是国内源适配问题
