### ISSUE TITLE
如何只制作ubuntu 22.04LTS的orangepi-config工具的deb包

### ISSUE THREAD

**Issue by 124ffee** [orangepi-xunlong/orangepi-build#104]
如何只制作ubuntu 22.04LTS的orangepi-config工具的deb包，我想要给香橙派5plus第三方ubuntu使用orangepi-config工具这样我就能启动一些东西。

**Comment by orangepi-xunlong** [comment]
目前没有这样的方法，编译镜像会自动编译orangepi-config这个包，也花费不了多少时间。
