### ISSUE TITLE
Error in function; system unsupported - please update script to Debian 12 (Server) / Ubuntu 23.04 LTS (Server)

### ISSUE THREAD

**Issue by Paderman** [orangepi-xunlong/orangepi-build#105]
Please update to Debian 12 (Server) / Ubuntu 23.04 LTS (Server) because older versions are a little bit obsolete.
The script give me only Debian 10 "Buster" and the old Ubuntu from 2018 and 2020.

And when I choose a option to build, I get error like
`ERROR in function prepare_host [ general.sh:700 ]`
`It seems you ignore the documentation and run unsupported build system: bullseye`

What for "documentation"?

Used host: Debian 12 "Bookworm" (amd64).
For system: Orange Pi Zero2

Thank you :-)

**Edit**
The fork https://github.com/qitas/orangepi is _next_ but I get error messages too 😢

`ERROR in function prepare_host [ ./build.sh:305 -> scripts/main.sh:628 -> scripts/main.sh:433 -> scripts/main.sh:1467 -> scripts/main.sh:0 ]`
`It seems you ignore the documentation and run unsupported build system: bullseye`

**Comment by orangepi-xunlong** [comment]
http://www.orangepi.org/orangepiwiki/index.php/Orange_Pi_Zero_3#Linux_SDK.E2.80.94.E2.80.94orangepi-build_instruction

**Comment by puckettgw** [comment]
Using the next branch still doesn't allow to build a bookworm image on orangepi 5 plus.

**Comment by Paderman** [comment]
Is it possible to build for latest Debian?

I use the officially version of latest Debian, but it seems be a bug, if I want to use Docker... The System shut down after while, all LED's are turned off and I must re-plugged power...
