### ISSUE TITLE
cp: 无法创建普通文件'/home/zhouhua/orangepi-build/.tmp/rootfs-5850629f-f891-457d-a3d7-748e88535c9a/usr/share,/sounds/alsa/':没有那个文件或目录

### ISSUE THREAD

**Issue by windskyxb** [orangepi-xunlong/orangepi-build#109]
在编译orangepi5的minimal版本bullseye时提示：cp: 无法创建普通文件'/home/zhouhua/orangepi-build/.tmp/rootfs-5850629f-f891-457d-a3d7-748e88535c9a/usr/share,/sounds/alsa/':没有那个文件或目录
![image](https://github.com/orangepi-xunlong/orangepi-build/assets/60282327/38afcd5e-91de-4e87-8cc8-b37d77b90ba0)
怀疑是创建rootfs时没有安装alsa-utils这个包

**Comment by orangepi-xunlong** [comment]
不建议用minimal版本，没有测试过。
