### ISSUE TITLE
How to use Orange Pi 4 with LCD TFT TOUCH SCREEN 10.1inch

### ISSUE THREAD

**Issue by aehiro** [orangepi-xunlong/orangepi-build#11]
How to use Orange Pi 4 with LCD TFT TOUCH SCREEN 10.1inch
LCD IC NT35521
Your document is very old

**Comment by orangepi-xunlong** [comment]
Sorry, you can first refer to the Chinese version of the manual, which has detailed instructions, the English version is still being updated, or feedback to the customer service, they will teach you the detailed use method.
