### ISSUE TITLE
How to make only the deb package of the orangepi-config tool for ubuntu 22.04LTS. I want to use the orangepi-config tool for Orange Pi 5plus third-party ubuntu so that I can start something.

### ISSUE THREAD

**Issue by kuolung1** [orangepi-xunlong/orangepi-build#111]
How to make only the deb package of the orangepi-config tool for ubuntu 22.04LTS. I want to use the orangepi-config tool for Orange Pi 5plus third-party ubuntu so that I can start something.

**Comment by orangepi-xunlong** [comment]
There is no way to compile orangepi-config only.
