### ISSUE TITLE
opi5 plus pulseaudio failed to start when lock autologin.

### ISSUE THREAD

**Issue by wurong98** [orangepi-xunlong/orangepi-build#145]
硬件：orangepi 5Plus
镜像：Orangepi5plus_1.0.8_ubuntu_focal_desktop_xfce_linux5.10.160.img
内核：Linux D152402102788IY 5.10.160-rockchip-rk3588 https://github.com/orangepi-xunlong/orangepi-build/pull/1.0.8 SMP Fri Nov 10 17:58:32 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

* 将镜像烧录到SD卡后
* 关闭autologin sudo disable_desktop_autologin.sh
再次重启输入密码。
声卡功能异常

![1427a007ce16a63f28f2b35d200dfea](https://github.com/orangepi-xunlong/orangepi-build/assets/22260281/7aa5c2c2-2ac4-483d-9823-673a613ce882)

**Comment by kingsimba** [comment]
之前复现步骤没有写清楚。是需要创建一个新的用户，并用这个用户登录，才能复现问题。

原因是 orangepi 和 新创建的用户同时登录，会有多个 pulseaudio 进程抢占声音设备。

解决方法：禁用 orangepi 用户，让它无法登录。

**Comment by wurong98** [comment]
pluseaudio config error
