### ISSUE TITLE
orangepi-check-first-login.sh not compatible with sh

### ISSUE THREAD

**Issue by matt335672** [orangepi-xunlong/orangepi-build#15]
Hi,

I'm one of the maintainers of the [xrdp](/neutrinolabs/xrdp) project.

As part of investigating issue neutrinolabs/xrdp#2044, we've found that  `/etc/profile.d/orangepi-check-first-login.sh` is not compatible with `sh`, but assumes the user is using `bash`. This can be seen with:-

```
sh -x /etc/profile
. . .
/etc/profile: 20: /etc/profile.d/orangepi-check-first-login.sh: Syntax error: "(" unexpected
```

This means that any user configured with `/bin/sh` (and maybe other shells) will not be able to log in.

We found this issue also with Armbian a while ago. I raised it with them as armbian/build#2185, and then later raised a PR armbian/build#2190 to resolve it.

As far as I can see, a similar PR should be applied to OrangePI. Would you be happy for me to raise one?

Thanks.

**Comment by orangepi-xunlong** [comment]
Of course, thanks for your feedback!
