### ISSUE TITLE
R1 Plus LTS fan controller

### ISSUE THREAD

**Issue by jkearneyma** [orangepi-xunlong/orangepi-build#21]
I'm not sure if this is the right place for this, or even if you consider it a bug, but:

Should the PWM fan interface be enabled by default in the build?  From the schematic, the fan interface is on PWM2, but the device tree configuration here is

 pwm2: pwm@ff1b0020 {
  compatible = "rockchip,rk3328-pwm";
  reg = <0x0 0xff1b0020 0x0 0x10>;
  clocks = <&cru 60>, <&cru 214>;
  clock-names = "pwm", "pclk";
  pinctrl-names = "default";
  pinctrl-0 = <&pwm2_pin>;
  #pwm-cells = <3>;
  status = "disabled";
 };

Changing the status to "okay" makes the pwm device appear in /sys, although I have not yet succeeded in getting a fan to actually run when connected to the board.

**Comment by baiywt** [comment]
Hi, pwm2 has been enabled in DTS. See https://github.com/orangepi-xunlong/linux-orangepi/commit/9a579db3efc1085608cb8c13dd225271478d66e1
