### ISSUE TITLE
关于orangepi 4B的支持

### ISSUE THREAD

**Issue by higithubhi** [orangepi-xunlong/orangepi-build#26]
在next分支有rk3399芯片的orangepi 4 lts 的 focal版本支持，请问能不能添加orangepi 4B 的 focal

**Comment by orangepi-xunlong** [comment]
你好，下周适配下Orange  Pi 4B，谢谢！

**Comment by orangepi-xunlong** [comment]
next分支已添加OrangePi 4/4B的支持。
