### ISSUE TITLE
Orange Pi 4 LTS官网能提供带KVM模块UBUNTU or debian镜像吗？

### ISSUE THREAD

**Issue by yan-ace62** [orangepi-xunlong/orangepi-build#28]
香橙派官网提供的ubuntu镜像不带kvm模块，看起来是KERNEL_TARGET="legacy"模式内核配置编译得。能提供KERNEL_TARGET="current"模式内核配置编译得镜像吗？ 看这个内核配置开启了KVM相关功能。

**Comment by orangepi-xunlong** [comment]
你好，后面更新镜像可以把这个配置打开，不过目前的话建议你自己直接打开对应的内核配置编译内核使用下，毕竟源码都是开放的，手册也提供了内核的编译方法。谢谢！
