### ISSUE TITLE
OPi Zero 2 GPU Drivers?

### ISSUE THREAD

**Issue by NetuserPRO46** [orangepi-xunlong/orangepi-build#29]
Hi, i have a problem with mainline kernel panfrost driver. I'm compiled it into kernel and `dmesg | grep panfrost` shows nothing.
However, official arm mali driver doesn't work too. System just can't detect gpu. I think there's problem in device tree.

**Comment by orangepi-xunlong** [comment]
Hi, which code are you using?

orangepi-build next branch: Debian12 Linux5.16 GPU is ok.

![图片](https://user-images.githubusercontent.com/10287101/163900823-d93a615e-af7b-426c-93ec-d2c50f22b45b.png)

![图片](https://user-images.githubusercontent.com/10287101/163900861-24bff7b2-7dc5-4c06-b972-af531a295c34.png)

![图片](https://user-images.githubusercontent.com/10287101/163900901-9a2ed93f-ccc4-4248-9e79-6ad3d0cd8568.png)

![图片](https://user-images.githubusercontent.com/10287101/163900905-1403f34a-1d74-471e-bd6a-3b652f8e59e5.png)

![图片](https://user-images.githubusercontent.com/10287101/163900881-a6b8c2ae-214f-4c6b-ad9d-5d9b962e4e88.png)

**Comment by NetuserPRO46** [comment]
How do i compile the 5.16 kernel?

**Comment by NetuserPRO46** [comment]
Thanks for reply!
