### ISSUE TITLE
Orange pi zero 2

### ISSUE THREAD

**Issue by liberodark** [orangepi-xunlong/orangepi-build#3]
Hi,

Im a batocera contributor and we have implemented orange zero 2 support but we are currently stuck on startup on the graphics part (panfrost).
https://github.com/apritzel/linux/commits/h616-v5
I wanted to know if there has been any progress on this point on your side.
Because this is something that was not yet implemented in the sources.

Best Regards

**Comment by orangepi-xunlong** [comment]
Not yet, thank you!
