### ISSUE TITLE
居然不支持国产操作系统deepin

### ISSUE THREAD

**Issue by worldflyingct** [orangepi-xunlong/orangepi-build#30]
deepin运行lsb_release -sc得到的是apricot，无法运行。

**Comment by worldflyingct** [comment]
目前我的非官方处理方式是修改./scripts/general.sh
将695行添加apricot让其不报错，可以往下执行了。

**Comment by orangepi-xunlong** [comment]
你好，deepin没有测试过，编译环境麻烦参考下用户手册，谢谢！
