### ISSUE TITLE
build for rootfs broke - orange pi zero

### ISSUE THREAD

**Issue by ixnisarg** [orangepi-xunlong/orangepi-build#31]
o.k. ] Installing base system [ Stage 1/2 ]
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file http://localhost:3142/mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/focal/Release

**Comment by orangepi-xunlong** [comment]
`./build.sh DOWNLOAD_MIRROR=""`

Hi, Please try this command. Thanks!
