### ISSUE TITLE
Error on Installing base system

### ISSUE THREAD

**Issue by AlienWolfX** [orangepi-xunlong/orangepi-build#32]
Good day!, I'm having trouble compiling orangepi-one image in which an error occur on Installing base system attached below is the screenshot of the error thanks!. Btw I'm running on Ubuntu 18.04.

![image](https://user-images.githubusercontent.com/60495687/167113115-cf2ce7f7-39ed-4173-bda5-25e614f5dcff.png)

**Comment by orangepi-xunlong** [comment]
`wget https://ftp-master.debian.org/keys/release-10.asc -qO- | gpg --import --no-default-keyring --keyring /usr/share/keyrings/debian-archive-keyring.gpg >/dev/null 2>/dev/null`

Hi, Please try this command and run orangepi-build again.

Thanks!

**Comment by AlienWolfX** [comment]
Thank you.
