### ISSUE TITLE
Enable NEON in kernel on the Orange Pi Zero 2

### ISSUE THREAD

**Issue by Darkyere** [orangepi-xunlong/orangepi-build#40]
Would it be possible to compile the kernel with NEON SIMD on the Orange Pi Zero 2?

Found a reference about it here 

[Enabling the NEON unit in a Linux custom kernel](https://developer.arm.com/documentation/den0018/a/Compiling-NEON-Instructions/Vectorization/Enabling-the-NEON-unit-in-a-Linux-custom-kernel) 

But I am not capable of doing it my self and somehow installing the kernel after it's build.

**Comment by orangepi-xunlong** [comment]
First you can check to see if the kernel configuration has been turned on.

The kernel compilation method can be referred to the user manual.

https://drive.google.com/drive/folders/1T7NCV5ZBg1TrB1q_QUQ93GMbq0IlKLFn
