### ISSUE TITLE
error: gpg failed to sign the data

### ISSUE THREAD

**Issue by e190** [orangepi-xunlong/orangepi-build#41]
CPU configuration:
480000 - 1512000 with ondemand
Displaying message: Preparing host info
Displaying message: Build host OS release focal info
Displaying message: Syncing clock cn.pool.ntp.org info
Displaying message: Checking for external GCC compilers  info
pub   rsa2048 2011-01-04 [SC]
      873D6A08B28A5167B466D9D4D47877808F427EAF
uid           [ 未知 ] Linaro Toolchain Builder <michael.hope+cbuild@linaro.org>

pub   rsa4096 2015-03-16 [SC]
      DF00FAF1C577104B50BF1D0093D6889F9F0E78D5
uid           [ 未知 ] Igor Pecovnik <igor@armbian.com>
uid           [ 未知 ] Igor Pecovnik (Ljubljana, Slovenia) <igor.pecovnik@gmail.com>
sub   rsa4096 2015-03-16 [E]

gpg: 没有已签名的数据
gpg: can't hash datafile: 无数据
Displaying message: ERROR in function download_and_verify general.sh:1031 err
Displaying message: verification failed  err
Displaying message: Process terminated  info

**Comment by orangepi-xunlong** [comment]
提供信息麻烦全面点，不要只丢一个错误Log
