### ISSUE TITLE
Orangepi 4LTS build Debian can't boot to xfce Desktop

### ISSUE THREAD

**Issue by kismeter** [orangepi-xunlong/orangepi-build#43]
Hi,

I using following command to build Debian full image for OrangePI 4LTS, 
```
sudo ./build.sh  BOARD=orangepi4-lts BRANCH=current BUILD_OPT=image RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no DESKTOP_ENVIRONMENT=xfce DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base DESKTOP_APPGROUPS_SELECTED="desktop_tools programming" COMPRESS_OUTPUTIMAGE=sha,gpg,img 
```
but the device only boot to console and not enter into xfce desktop, when command shows shat no startx and startxfce4. is there something missing using the build.sh?

Thanks.

**Comment by orangepi-xunlong** [comment]
Please check that the rootfs compile size is correct.
