### ISSUE TITLE
No aw859a-wifi.service

### ISSUE THREAD

**Issue by wutong233** [orangepi-xunlong/orangepi-build#47]
“For AW859A driver source was include in Allwinner H616 Orange Pi Zero2 BSP, you can get it from orangepi-build repository",linux-sunxi.org said.But there is no any wifi driver for aw859a so that the armbian for orangepi zero 2 cant activate wifi.

**Comment by orangepi-xunlong** [comment]
- kernel 
https://github.com/orangepi-xunlong/linux-orangepi/tree/orange-pi-4.9-sun50iw9
https://github.com/orangepi-xunlong/linux-orangepi/tree/orange-pi-5.16-sunxi64


- Aw859a: 
drivers/net/wireless/uwe5622
