### ISSUE TITLE
Orange pi zero 2 can not reboot or shutdown

### ISSUE THREAD

**Issue by tarekmuallim** [orangepi-xunlong/orangepi-build#50]
Hello,

When I am trying to shutdown or reboot, it stuck at shutdown after giving message:
`systemd-shutdown[1]: Waiting for process: grep, lscpu
`

Any idea why this is happening?  

The OS image:
Orangepizero2_3.0.6_ubuntu_jammy_desktop_xfce_linux5.16.17

**Comment by orangepi-xunlong** [comment]
[sun50i-h616-orangepi-zero2.zip](https://github.com/orangepi-xunlong/orangepi-build/files/10244786/sun50i-h616-orangepi-zero2.zip)

Please update this dtb.

**Comment by tarekmuallim** [comment]
Thank you, this works.

**Comment by DX-persist** [comment]
Could you can tell me how to do that?

**Comment by DX-persist** [comment]
Could you can tell me how to do that?

**Comment by DX-persist** [comment]
Could you can tell me how to do that?

**Comment by DX-persist** [comment]
Could you can tell me how to do that?
