### ISSUE TITLE
什么时候加入3588s？

### ISSUE THREAD

**Issue by longcat99** [orangepi-xunlong/orangepi-build#51]
什么时候加入3588s?

**Comment by zhuzhu-Top** [comment]
![image](https://user-images.githubusercontent.com/35734511/206829593-f52d3e21-a58d-4ac5-9f72-5f6bb7d265e0.png)

编译内核的时候有3588s,你看看是不是这个，我也想编译这个

**Comment by longcat99** [comment]
对,就是这个

**Comment by longcat99** [comment]
我没注意看，需要切换分支
