### ISSUE TITLE
Check official firmware SHA failed

### ISSUE THREAD

**Issue by AKopytenko** [orangepi-xunlong/orangepi-build#52]
Checksum from the archive with the firmware [Ubuntu Image](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi800.html) from the official site 
_[from file Orangepi800_3.0.8_ubuntu_jammy_desktop_xfce_linux5.18.5.img.sha]_:
`4cfd9e022950f4f29c3e21a12fb2555849eb1ddd407dfd0fcecc512477c3f945`

The result of calculating the real checksum of the image after unpacking the downloaded archive 
_[file Orangepi800_3.0.8_ubuntu_jammy_desktop_xfce_linux5.18.5.img]_:
`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

Am I doing something wrong, or is the checksum information simply not updated?
Or was the firmware file really changed?

**Comment by orangepi-xunlong** [comment]
![图片](https://user-images.githubusercontent.com/10287101/208562237-875da9ea-f632-47b0-9c6e-1f41494c59f0.png)

No problem.
