### ISSUE TITLE
How to build ds1307 module for orange pi 5?

### ISSUE THREAD

**Issue by pourfard** [orangepi-xunlong/orangepi-build#54]
Hi, 

I need rtc-ds1307 driver. So I downloaded `linux-5.10.110` kernel source code and get the config with command 

`cp -v /boot/config-$(uname -r) .config` 

and edited the config file and set these lines:

```
CONFIG_RTC_DRV_DS1307=m
CONFIG_RTC_DRV_DS1307_CENTURY=y
```

Then used `make` and `make modules` to get the `rtc-ds1307.ko`. But when I try to insert the module using this command 

`insmod rtc-ds1307.ko` 

 I get

 `insmod: ERROR: could not insert module rtc-ds1307.ko: Invalid module format`. 

and when running:

`modprobe rtc-ds1307`

I get:

`modprobe: ERROR: could not insert 'rtc_ds1307': Exec format error`

What is the problem and how can I solve it?

**Comment by orangepi-xunlong** [comment]
Please use orangepi-build to compile the kernel. thanks!
