### ISSUE TITLE
sunxi-tools for RK3399

### ISSUE THREAD

**Issue by AndreiCherniaev** [orangepi-xunlong/orangepi-build#6]
I am making Ubuntu for my Orange Pi 4B with Rockchip RK3399 using _orangepi-build_. 

File orangepi-build/scripts/main.sh contains
```
	fetch_from_repo "https://github.com/linux-sunxi/sunxi-tools" "${EXTER}/cache/sources/sunxi-tools" "branch:master"
	fetch_from_repo "https://github.com/armbian/rkbin" "${EXTER}/cache/sources/rkbin-tools" "branch:master"

	if [[ $BOARD == orangepi4 ]]; then
		fetch_from_repo "https://github.com/orangepi-xunlong/rk3399_gst_xserver_libs.git" "${EXTER}/cache/sources/rk3399_gst_xserver_libs" "branch:main"
	fi
```

I think I don't need sunxi-tools. When I download it I just spend time. May be @orangepi-xunlong should use **elif** to download sunxi-tools?

**Comment by orangepi-xunlong** [comment]
You can also set **IGNORE_UPDATES="yes"** in **userpatches/config-default.conf** so that the source code will not be updated with each compilation.
