### ISSUE TITLE
orangepi-config in custom image

### ISSUE THREAD

**Issue by beriberikix** [orangepi-xunlong/orangepi-build#60]
I built my own image (#57) but it didn't include utilities like `orangepi-config`. Do I need enable something for it to be built and included?

**Comment by leeboby** [comment]
Choose **Standard image with console interface** or **Image with desktop environment**.

With such a powerful board, why would you choose to build the weakest system?

**Comment by beriberikix** [comment]
Ah, just tried rebuilding with the standard CLI instead of minimal and it was there.

I intend to use the full power of the board! I prefer to start with a minimal version so I have better control over which packages are installed, since many in APT are out of date.
