### ISSUE TITLE
orange pi zero 2 no /dev/i2c-*

### ISSUE THREAD

**Issue by DavidVorick** [orangepi-xunlong/orangepi-build#61]
I am trying to use the GPIOs on the Orange Pi Zero 2, specifically the i2c pins. When I look at /dev/, I see /dev/i2c-0 (which is for HDMI), but I do not see any other i2c options. 

I read through the manual (https://linux-sunxi.org/images/7/72/OrangePi_Zero2_H616_User_Manual_v1.0.pdf) and set up wiringOP, but got stuck because it still could not find /dev/i2c-3 or /dev/i2c-5.

How do I configure the build so that I can use i2c?

**Comment by leeboby** [comment]
If the Linux5.16 image is used, please add **overlays=i2c3** in **/boot/orangepiEnv.txt**.
 
```
orangepi@orangepi:~$ sudo vim /boot/orangepiEnv.txt
overlays=i2c3
```

There is no i2c5 for zero2 in 26pin.

**Comment by DavidVorick** [comment]
I am happy to confirm that this solved the issue for me, my i2c is now working as hoped.

Is there some place I should have looked in the documentation?

**Comment by leeboby** [comment]
https://drive.google.com/drive/folders/1ToDjWZQptABxfiRwaeYW1WzQILM5iwpb

![图片](https://user-images.githubusercontent.com/26613156/211147462-686c03c1-1c62-4b50-8557-93272ba81511.png)

![图片](https://user-images.githubusercontent.com/26613156/211147492-d72b3df8-a110-4e88-949f-fcc79e2189dd.png)
