### ISSUE TITLE
missing Orange Pi 5?

### ISSUE THREAD

**Issue by homonto** [orangepi-xunlong/orangepi-build#64]
What am I doing wrong?
I wanted to compile for Orange Pi 5 but I don't see it in the menu

<img width="820" alt="Screenshot 2023-01-28 at 07 40 26" src="https://user-images.githubusercontent.com/46562447/215253710-03b9e856-a02b-43b7-8097-c90ed6844237.png">

**Comment by ProKn1fe** [comment]
It's in different branch https://github.com/orangepi-xunlong/orangepi-build/tree/next

**Comment by homonto** [comment]
superb! do I need to run this script on the target orange pi 5 or I can do it on any machine?

**Comment by orangepi-xunlong** [comment]
Ubuntu 22.04, on opi5 or x64 pc.
