### ISSUE TITLE
Orange Pi Focal with Linux 4.4.179-rk3399

### ISSUE THREAD

**Issue by AndreiCherniaev** [orangepi-xunlong/orangepi-build#7]
![IMG_20210422_184428_489](https://user-images.githubusercontent.com/27889022/115800506-d3252100-a3eb-11eb-8cbc-961e929c196f.jpg)
I build Ubuntu 18 for my Orange Pi 4B using orangepi-build script.
After I make
```
sudo apt install ubuntu-release-upgrader-core
do-release-upgrade -d -f DistUpgradeViewNonInteractive
```

It is very interesting! My Orange Pi 4B works good! May be @orangepi-xunlong add option to build Ubuntu 20 directly from script? Or just build Ubuntu 20 instead of Ubuntu 18?

**Comment by orangepi-xunlong** [comment]
Yes, Ubuntu Focal starts on Orange Pi 4B, but some features are not available, such as the camera, so there's no compilation option for Ubuntu Focal.
