### ISSUE TITLE
opi Zero LTS support

### ISSUE THREAD

**Issue by eldarbr** [orangepi-xunlong/orangepi-build#72]
Is there support of Orange Pi Zero LTS (which has allwinner H3 and 512 mb ram and wifi on board)? Didn't find relevant option in the list to build full image.

**Comment by orangepi-xunlong** [comment]
Use orange pi zero.

**Comment by eldarbr** [comment]
As orange pi zero is based on allwinner h2, the script provides only that option - h2. Isn't it a problem for zero lts (allwinner h3)?
