### ISSUE TITLE
Orange Pi Zero 2 - UART5

### ISSUE THREAD

**Issue by rbn920** [orangepi-xunlong/orangepi-build#73]
Page 144 of the Orange Pi Zero 2 give instructions on enabling and testing the UART5 pins. The loopback test does not display results as the manual shows. As an additional test I connected the Orange Pi Zero 2 to a Raspberry Pi4 via UART pins and opened minicom on each device. The Orange Pi Zero 2 will receive but not send.

**Comment by orangepi-xunlong** [comment]
Which linux image?

**Comment by rbn920** [comment]
Orangepizero2_3.0.6_debian_bullseye_server_linux5.16.17

**Comment by orangepi-xunlong** [comment]
Please add overlays=uart5 in /boot/orangepiEnv.txt.

orangepi@orangepi:~$ sudo vim /boot/orangepiEnv.txt
overlays=uart5

**Comment by rbn920** [comment]
That was done, just as noted in the manual. Testing using gpio as also noted in the manual does yield correct results. Also when connected to a Pi4 I could receive commands but not send them using minicom.

**Comment by orangepi-xunlong** [comment]
???  The loopback test does not display results as the manual shows. ???

**Comment by rbn920** [comment]
The manual (p. 145) has you wire the tx pin to the rx pin (8 to 10) then run `gpio serial /dev/ttyS5` with results like:
```
Out: 0: -> 0
Out: 1: -> 1
...
```
but instead I get:
```
Out: 0: 
Out: 1: 
...
```

Also, this is all from OrangePi_Zero2_H616_User manual_v3.7.

**Comment by orangepi-xunlong** [comment]
Are the pins connected correctly？

If the settings are all correct, the hardware is broken.

**Comment by rbn920** [comment]
Yes, the pins are connected correctly. I guess my board is bad then.
