### ISSUE TITLE
基于docker的OPIzero镜像编译

### ISSUE THREAD

**Issue by lozenyin** [orangepi-xunlong/orangepi-build#74]
在docker中运行orangepi_build中的build.sh。出现一下错误
`
[ o.k. ] Creating partitions [ root: ext4 ]
[ error ] ERROR in function check_loop_device [ image-helpers.sh:82 ]
[ error ] Device node /dev/loop19p1 does not exist
[ o.k. ] Process terminated
[ o.k. ] Unmounting [ /work/orangepi-build/.tmp/rootfs-current-orangepizero-focal-no-no/ ]
[ error ] ERROR in function unmount_on_exit [ image-helpers.sh:69 ]
[ error ] debootstrap-ng was interrupted
[ o.k. ] Process terminated
`
请问一下这个问题我该怎么处理？

**Comment by orangepi-xunlong** [comment]
docker没有测试过能用，按照手册的说明来。
