### ISSUE TITLE
[ error ] ERROR in function prepare_host [ general.sh:657 ] [ error ] Running this tool on non x86-x64 build host in not supported

### ISSUE THREAD

**Issue by niranjanadhav** [orangepi-xunlong/orangepi-build#79]
opi@orangepizero2:~/orangepi-build$ sudo ./build.sh
[ o.k. ] Using config file [ /home/opi/orangepi-build/userpatches/config-example.conf ]
[ o.k. ] Preparing [ host ]
[ .... ] Please read documentation to set up proper compilation environment
[ .... ] http://www.orangepi.org
[ error ] ERROR in function prepare_host [ general.sh:657 ]
[ error ] Running this tool on non x86-x64 build host in not supported
[ o.k. ] Process terminated

**Comment by orangepi-xunlong** [comment]
**Running this tool on non x86-x64 build host in not supported**
