### ISSUE TITLE
libkms.so.1

### ISSUE THREAD

**Issue by AndreiCherniaev** [orangepi-xunlong/orangepi-build#8]
After build full OS using [orangepi-build](https://github.com/orangepi-xunlong/orangepi-build/issues/new) I try upgrade packages of my Ubuntu 18 server
The end of log is
```
The following packages will be upgraded:
  libcaca0
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 192 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports bionic-security/main arm64 libcaca0 arm64 0.99.beta19-2ubuntu0.18.04.2 [192 kB]
Fetched 192 kB in 3s (76.8 kB/s)   
(Reading database ... 33743 files and directories currently installed.)
Preparing to unpack .../libcaca0_0.99.beta19-2ubuntu0.18.04.2_arm64.deb ...
Unpacking libcaca0:arm64 (0.99.beta19-2ubuntu0.18.04.2) over (0.99.beta19-2ubuntu0.18.04.1) ...
Setting up libcaca0:arm64 (0.99.beta19-2ubuntu0.18.04.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
/sbin/ldconfig.real: /usr/lib/libdrm.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/liborc-test-0.4.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libdrm_radeon.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libdrm_amdgpu.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libdrm_freedreno.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libdrm_nouveau.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libkms.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/liborc-0.4.so.0 is not a symbolic link

```

I try build Qt with KMS. This is a big problem because "/sbin/ldconfig.real: /usr/lib/libkms.so.1 is not a symbolic link"
I need bring back KMS to my Ubuntu 18 server. How I can solve it?

I also can make  _sudo /sbin/ldconfig_ to get this long errors list...

**Comment by orangepi-xunlong** [comment]
Sorry, this goes beyond the problem orangepi-build needs to solve, and Google may be a good solution.

**Comment by AndreiCherniaev** [comment]
@orangepi-xunlong there wasn't same problem on previous Ubuntu 18 build! You can verify that no problem using backup image from your [googledrive](http://www.orangepi.org/downloadresources/OrangePi4B/2020-01-03/orangepi3_f9433ee3d9493fd6fc711c065d.html). 

I am googling a lot of but I can't solve problems. Please help.

**Comment by orangepi-xunlong** [comment]
How to repeat, please send the detailed steps, thanks!

**Comment by AndreiCherniaev** [comment]
> How to repeat, please send the detailed steps, thanks!

1) Build your Ubuntu 18 with graphics
2) open console and 
`sudo /sbin/ldconfig`
so you can see problems... 
3) Try to do this steps also on your old Ubuntu 18 build!

**Comment by orangepi-xunlong** [comment]
The issue has been resolved and you can download the latest image for testing.

If you compile the image yourself, go to the following directory and update the code with the **git pull** command, then recompile the linux image.

`orangepi-build/external/cache/sources/rk3399_gst_xserver_libs`
