### ISSUE TITLE
 error ] ERROR in function download_and_verify [ general.sh:1031 ] [ error ] verification failed

### ISSUE THREAD

**Issue by niranjanadhav** [orangepi-xunlong/orangepi-build#81]
[ error ] ERROR in function download_and_verify [ general.sh:1031 ]
[ error ] verification failed
[ o.k. ] Process terminated

**Comment by orangepi-xunlong** [comment]
If you want to solve a problem, it is better to provide detailed information than a small piece of error information for someone to guess.
