### ISSUE TITLE
docker 

### ISSUE THREAD

**Issue by Metear** [orangepi-xunlong/orangepi-build#83]
在docker 中使用ubuntu16.04镜像，执行./build.sh，然后就一直重复显示：
[ warn ] Package manager is running in the background. [ Please wait! Retrying in 30 sec ]

**Comment by orangepi-xunlong** [comment]
按照手册的说明来操作。

**Comment by kelvinvoon03** [comment]
I might be too late here, but on docker you'll need the `psmisc` package.

**Comment by takase1121** [comment]
Sorry if this is too late, but you'll need the `psmisc` package.
You'll also need `python3-setuptools`.
