### ISSUE TITLE
Will there be realtime-enabled kernel  for orangepi5B or 5 plus?

### ISSUE THREAD

**Issue by xibeisiber** [orangepi-xunlong/orangepi-build#86]
Hi,

Will there be realtime-enabled kernel  for orangepi5B or 5 plus? 
I tried to patch PREEMPT_RT into kernel but failed...

Thanks!

**Comment by orangepi-xunlong** [comment]
https://github.com/orangepi-xunlong/linux-orangepi/tree/orange-pi-5.10-rk35xx-rt

https://github.com/orangepi-xunlong/orangepi-build/blob/next/external/config/kernel/linux-rockchip-rk3588-legacy-rt.config
