### ISSUE TITLE
orange pi 5 rk3588S image wont build

### ISSUE THREAD

**Issue by espero-dev** [orangepi-xunlong/orangepi-build#91]
the image wont build i tried everything to try to get it but it wont work help me please i wanna make a os for it

**Comment by orangepi-xunlong** [comment]
If you have problems compiling on X86 computers, you can try compiling on the development board.

**Comment by espero-dev** [comment]
like compile on the orange pi?

**Comment by orangepi-xunlong** [comment]
http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-pi-5.html

![图片](https://github.com/orangepi-xunlong/orangepi-build/assets/10287101/35cb3880-57e3-428b-b83a-a26d45197817)

**Comment by espero-dev** [comment]
im to lazy to read it should i build it on the orange pi 5
