### ISSUE TITLE
How can i build kernel for Orange Pi Zero 3?

### ISSUE THREAD

**Issue by csoftware-arigpt** [orangepi-xunlong/orangepi-build#94]
Is there any difference between the build for H616 (Zero 2) and H618 (Zero 3)?

**Comment by Alex-Lin** [comment]
The document indicate that we need to checkout the branch which is named "next"  to build kernel for H618

**Comment by ShohninDmitriy** [comment]
> The document indicate that we need to checkout the branch which is named "next" to build kernel for H618

The compiled image on Orange PiZero 3 4Gb does not start.

```
U-Boot SPL 2021.07-orangepi (Aug 24 2023 - 19:39:25 +0300)
DRAM: 4096 MiB
Trying to boot from MMC1
```

**Comment by orangepi-xunlong** [comment]
Please take a look at the user manual. It has compilation instructions. thanks.

http://www.orangepi.org/orangepiwiki/index.php/Orange_Pi_Zero_3#Linux_SDK.E2.80.94.E2.80.94orangepi-build_instruction
